import React from "react";
import Studentinfo from "./Studentinfo";
function AttendanceTable() {
  // {props.name}</td>
  //     <td>{props.roll}</td>
  //     <td>{props.group}</td>
  //     <td>{props.attendance}</td>
  //     <td>{props.attendancepercentage}
  return (
    <div>
      <h1>Student Attendance</h1>
      <table className="max-table">
        <h4>
          <Studentinfo
            name="NAME"
            roll="ROLL"
            group="GROUP"
            attendance="ATTENDANCE"
            attendancepercentage="PERCENTAGE"
          />
        </h4>
        <Studentinfo
          name="prince"
          roll="2110991065"
          group="3"
          attendance="A"
          attendancepercentage="75%"
        />
        <Studentinfo
          name="Rajit"
          roll="2110991129"
          group="3"
          attendance="p"
          attendancepercentage="86%"
        />
        <Studentinfo
          name="Piyush"
          roll="2110991012"
          group="3"
          attendance="p"
          attendancepercentage="95%"
        />
        <Studentinfo
          name="Sainirmit"
          roll="2110991231"
          group="3"
          attendance="A"
          attendancepercentage="14%"
          className="sai"
        />
        <Studentinfo
          name="Rohit"
          roll="2110991195"
          group="3"
          attendance="p"
          attendancepercentage="86%"
        />
        <Studentinfo
          name="prince"
          roll="2110991065"
          group="3"
          attendance="A"
          attendancepercentage="75%"
        />
        <Studentinfo
          name="Rajit"
          roll="2110991129"
          group="3"
          attendance="p"
          attendancepercentage="86%"
        />
        <Studentinfo
          name="Piyush"
          roll="2110991012"
          group="3"
          attendance="p"
          attendancepercentage="95%"
        />
        <Studentinfo
          name="Sainirmit"
          roll="2110991231"
          group="3"
          attendance="A"
          attendancepercentage="14%"
          className="sai"
        />
        <Studentinfo
          name="Rohit"
          roll="2110991195"
          group="3"
          attendance="p"
          attendancepercentage="86%"
        />
        <Studentinfo
          name="prince"
          roll="2110991065"
          group="3"
          attendance="A"
          attendancepercentage="75%"
        />
        <Studentinfo
          name="Rajit"
          roll="2110991129"
          group="3"
          attendance="p"
          attendancepercentage="86%"
        />
        <Studentinfo
          name="Piyush"
          roll="2110991012"
          group="3"
          attendance="p"
          attendancepercentage="95%"
        />
        <Studentinfo
          name="Sainirmit"
          roll="2110991231"
          group="3"
          attendance="A"
          attendancepercentage="14%"
          className="sai"
        />
        <Studentinfo
          name="Rohit"
          roll="2110991195"
          group="3"
          attendance="p"
          attendancepercentage="86%"
        />
        <Studentinfo
          name="prince"
          roll="2110991065"
          group="3"
          attendance="A"
          attendancepercentage="75%"
        />
        <Studentinfo
          name="Rajit"
          roll="2110991129"
          group="3"
          attendance="p"
          attendancepercentage="86%"
        />
        <Studentinfo
          name="Piyush"
          roll="2110991012"
          group="3"
          attendance="p"
          attendancepercentage="95%"
        />
        <Studentinfo
          name="Sainirmit"
          roll="2110991231"
          group="3"
          attendance="A"
          attendancepercentage="14%"
          className="sai"
        />
        <Studentinfo
          name="Rohit"
          roll="2110991195"
          group="3"
          attendance="p"
          attendancepercentage="86%"
        />
        <Studentinfo
          name="prince"
          roll="2110991065"
          group="3"
          attendance="A"
          attendancepercentage="75%"
        />
        <Studentinfo
          name="Rajit"
          roll="2110991129"
          group="3"
          attendance="p"
          attendancepercentage="86%"
        />
        <Studentinfo
          name="Piyush"
          roll="2110991012"
          group="3"
          attendance="p"
          attendancepercentage="95%"
        />
        <Studentinfo
          name="Sainirmit"
          roll="2110991231"
          group="3"
          attendance="A"
          attendancepercentage="14%"
          className="sai"
        />
        <Studentinfo
          name="Rohit"
          roll="2110991195"
          group="3"
          attendance="p"
          attendancepercentage="86%"
        />
        <Studentinfo
          name="prince"
          roll="2110991065"
          group="3"
          attendance="A"
          attendancepercentage="75%"
        />
        <Studentinfo
          name="Rajit"
          roll="2110991129"
          group="3"
          attendance="p"
          attendancepercentage="86%"
        />
        <Studentinfo
          name="Piyush"
          roll="2110991012"
          group="3"
          attendance="p"
          attendancepercentage="95%"
        />
        <Studentinfo
          name="Sainirmit"
          roll="2110991231"
          group="3"
          attendance="A"
          attendancepercentage="14%"
          className="sai"
        />
        <Studentinfo
          name="Rohit"
          roll="2110991195"
          group="3"
          attendance="p"
          attendancepercentage="86%"
        />
      </table>
    </div>
  );
}
export default AttendanceTable;
